# Setup
title:        Jan Meppe
tagline:      ""
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jan Meppe
  url:        http://Janmeppe.com 

# Gems
gems:
  - jekyll-paginate

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# highlighter 
highlighter: rouge
markdown: kramdown

# Syntax highlighting
kramdown:
    input: GFM 
    syntax_highlighter: rouge

# Google services
google_analytics: UA-78697215-1

# So you can post in the future ... post not visible
future: true

# Google analytics 
safe: true

remote_theme: "mmistakes/minimal-mistakes@4.16.4"

