# Setup
title:        Jan Meppe
tagline:      ""
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jan Meppe
  url:        http://Janmeppe.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# Syntax highlighting
highlighter: rouge

# Google services
google_analytics: UA-78697215-1

# So you can post in the future ... post not visible
# future: true

# Google analytics 
safe: true
