# Setup
title:        Jan Meppe
tagline:      ""
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jan Meppe
  url:        http://Janmeppe.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
